# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_framemodel_pictureview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framemodel',
            name='frame',
        ),
        migrations.AddField(
            model_name='framemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='frames'),
        ),
    ]
